export const emotionConfig: { [key: string]: { colorHex: string; colorName: string; emoji: string; } } = {
    "sadness": {"colorHex": "#3498db", "colorName": "blue", "emoji": "😔"},
    "disappointment": {"colorHex": "#95a5a6", "colorName": "gray", "emoji": "😞"},
    "grief": {"colorHex": "#2c3e50", "colorName": "dark blue", "emoji": "😢"},
    "neutral": {"colorHex": "#7f8c8d", "colorName": "light gray", "emoji": "😐"},
    "remorse": {"colorHex": "#e74c3c", "colorName": "red", "emoji": "😓"},
    "annoyance": {"colorHex": "#f39c12", "colorName": "orange", "emoji": "😠"},
    "caring": {"colorHex": "#1abc9c", "colorName": "turquoise", "emoji": "🤗"},
    "realization": {"colorHex": "#34495e", "colorName": "navy", "emoji": "💡"},
    "approval": {"colorHex": "#2ecc71", "colorName": "green", "emoji": "👍"},
    "admiration": {"colorHex": "#9b59b6", "colorName": "purple", "emoji": "😍"},
    "love": {"colorHex": "#ea9999", "colorName": "pink", "emoji": "❤️"},
    "disapproval": {"colorHex": "#c0392b", "colorName": "dark red", "emoji": "👎"},
    "joy": {"colorHex": "#f1c40f", "colorName": "yellow", "emoji": "😊"},
    "amusement": {"colorHex": "#f39c12", "colorName": "orange", "emoji": "😄"},
    "anger": {"colorHex": "#e74c3c", "colorName": "red", "emoji": "😡"},
    "nervousness": {"colorHex": "#e67e22", "colorName": "orange", "emoji": "😬"},
    "curiosity": {"colorHex": "#16a085", "colorName": "green", "emoji": "🤔"},
    "disgust": {"colorHex": "#27ae60", "colorName": "green", "emoji": "🤢"},
    "desire": {"colorHex": "#d35400", "colorName": "dark orange", "emoji": "🥰"},
    "fear": {"colorHex": "#34495e", "colorName": "navy", "emoji": "😨"},
    "gratitude": {"colorHex": "#2ecc71", "colorName": "green", "emoji": "🙏"},
    "confusion": {"colorHex": "#8e44ad", "colorName": "purple", "emoji": "😕"},
    "optimism": {"colorHex": "#f1c40f", "colorName": "yellow", "emoji": "😊"},
    "surprise": {"colorHex": "#f39c12", "colorName": "orange", "emoji": "😲"},
    "embarrassment": {"colorHex": "#e67e22", "colorName": "orange", "emoji": "😳"},
    "relief": {"colorHex": "#3498db", "colorName": "blue", "emoji": "😌"},
    "excitement": {"colorHex": "#e74c3c", "colorName": "red", "emoji": "😆"},
    "pride": {"colorHex": "#e67e22", "colorName": "orange", "emoji": "😌"}
  }